services:
  - type: web
    name: ramadvisor-backend-ultra-light
    env: python
    repo: https://github.com/MamyRAMA/RAMAdvisor.git
    branch: test-cloud
    rootDir: ./backend
    buildCommand: pip install -r requirements-ultra-light.txt
    startCommand: python main-ultra-light.py
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    scaling:
      minInstances: 0
      maxInstances: 1
